import { XilofoneKeyProps } from '../XilofoneKey';
import { Vector3 } from '@babylonjs/core';

const defaultWhiteKeyScaling = new Vector3(10, 1, 2.5);
const defaultYPosition = 0;
const pressedYPosition = -.5;

export const whiteKeys: XilofoneKeyProps[] = [
  {
    name: 'wk1',
    position: new Vector3(0, defaultYPosition, 0),
    pressedPosition: new Vector3(0, pressedYPosition, 0),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'C3',
  },
  {
    name: 'wk2',
    position: new Vector3(0, defaultYPosition, 3),
    pressedPosition: new Vector3(0, pressedYPosition, 3),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'B2',
  },
  {
    name: 'wk3',
    position: new Vector3(0, defaultYPosition, 6),
    pressedPosition: new Vector3(0, pressedYPosition, 6),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'A2',
  },
  {
    name: 'wk4',
    position: new Vector3(0, defaultYPosition, 9),
    pressedPosition: new Vector3(0, pressedYPosition, 9),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'G2',
  },
  {
    name: 'wk5',
    position: new Vector3(0, defaultYPosition, 12),
    pressedPosition: new Vector3(0, pressedYPosition, 12),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'F2',
  },
  {
    name: 'wk6',
    position: new Vector3(0, defaultYPosition, 15),
    pressedPosition: new Vector3(0, pressedYPosition, 15),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'E2',
  },
  {
    name: 'wk7',
    position: new Vector3(0, defaultYPosition, 18),
    pressedPosition: new Vector3(0, pressedYPosition, 18),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'D2',
  },
  {
    name: 'wk8',
    position: new Vector3(0, defaultYPosition, 21),
    pressedPosition: new Vector3(0, pressedYPosition, 21),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'C2',
  },
  {
    name: 'wk9',
    position: new Vector3(0, defaultYPosition, 24),
    pressedPosition: new Vector3(0, pressedYPosition, 24),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'B1',
  },
  {
    name: 'wk10',
    position: new Vector3(0, defaultYPosition, 27),
    pressedPosition: new Vector3(0, pressedYPosition, 27),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'A1',
  },
  {
    name: 'wk11',
    position: new Vector3(0, defaultYPosition, 30),
    pressedPosition: new Vector3(0, pressedYPosition, 30),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'G1',
  },
  {
    name: 'wk12',
    position: new Vector3(0, defaultYPosition, 33),
    pressedPosition: new Vector3(0, pressedYPosition, 33),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'F1',
  },
  {
    name: 'wk13',
    position: new Vector3(0, defaultYPosition, 36),
    pressedPosition: new Vector3(0, pressedYPosition, 36),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'E1',
  },
  {
    name: 'wk14',
    position: new Vector3(0, defaultYPosition, 39),
    pressedPosition: new Vector3(0, pressedYPosition, 39),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'D1',
  },
  {
    name: 'wk15',
    position: new Vector3(0, defaultYPosition, 42),
    pressedPosition: new Vector3(0, pressedYPosition, 42),
    color: '#FFFFFF',
    scaling: defaultWhiteKeyScaling,
    note: 'C1',
  },
];
